language: go

sudo: required
go:
  - "1.13.x"
dist: xenial
env:
  global:
    - OPERATOR_NAME=ibmcloud-iam-operator

services:
  - docker

go_import_path: ./

before_install:
  - source ./tools/travis/travis-env.sh
  - source ./hack/latest_tag
  - ./tools/travis/k8s-tools.sh
  - if [ ! -z "$BLUEMIX_API_KEY" ]; then ./tools/travis/set-kube-config.sh; fi
  - if [ ! -z "$BLUEMIX_API_KEY" ]; then ./tools/travis/bx-install.sh; fi
  - if [ ! -z "$BLUEMIX_API_KEY" ]; then ./tools/travis/bx-setup.sh; fi 

stages:
  - test
#  - deploy

jobs:
  include:    
    - stage: test
      script:
        - make codegen unittest e2etest
  #  - stage: deploy 
  #    script:
  #      - make build
  #    if: branch = master 