apiVersion: ibmcloud.ibm.com/v1alpha1
kind: AccessPolicy
metadata:
  name: mongodbuserpolicy
spec:
  subject:
    userEmail: avarghese@us.ibm.com
  roles:
    definedRoles:
      - Viewer
      - Administrator
  target:
    resourceGroup: Default
    serviceClass: databases-for-mongodb
    serviceID: fa1a1be1-ec2e-4294-b261-81c3400bf902

---    
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: AccessPolicy
metadata:
  name: mongodbservicepolicy
spec:
  subject:
    serviceID: ServiceId-fa27c539-a6cf-41d2-8cb0-2916da5f8e8a
  roles:
    definedRoles:
      - Viewer
      - Administrator
  target:
    resourceGroup: Default
    serviceClass: databases-for-mongodb
    serviceID: fa1a1be1-ec2e-4294-b261-81c3400bf902

--- 
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: AccessPolicy
metadata:
  name: mongodbgrouppolicy
spec:
  subject:
    accessGroupID: AccessGroupId-4099639d-95d2-4d78-ae6b-536f3891953c
  roles:
    definedRoles:
      - Viewer
      - Administrator
  target:
    resourceGroup: Default
    serviceClass: databases-for-mongodb
    serviceID: fa1a1be1-ec2e-4294-b261-81c3400bf902

---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: AccessGroup
metadata:
  name: mongodbnewgroup
spec:
  name: mongodbnewgroup
  description: A new access group to test access group controller
  userEmails:
      - avarghese@us.ibm.com
      - mvaziri@us.ibm.com
  serviceIDs:
    - ServiceId-3b9f026a-eb6e-495f-b104-95232d0c4a59
    - ServiceId-fa27c539-a6cf-41d2-8cb0-2916da5f8e8a   

--- 
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: AccessPolicy
metadata:
  name: mongodbnewgrouppolicy
spec:
  subject:
    accessGroupDef: 
      accessGroupName: mongodbnewgroup
      accessGroupNamespace: default
  roles:
    definedRoles:
      - Viewer
      - Administrator
  target:
    resourceGroup: Default
    serviceClass: databases-for-mongodb
    serviceID: fa1a1be1-ec2e-4294-b261-81c3400bf902